"""EMerge via simulation script — auto-generated by S-Params Studio.
   Uses 3D primitives (Box, Cylinder) — no PCB layouter."""


import datetime
import emerge_iron

from emerge_config import config
config.set_pardiso_threads(8)
config.set_acc_threads(10)

import math
import numpy as np
import emerge as em
import os, tempfile, shutil

#######################################################################################################################################
# DEFINE PROJECT NAME
#######################################################################################################################################
#from Plot_Results import ProjectName
ProjectName = "ViaAnalysis"


# Change current path to script file folder
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)

currDir = os.getcwd()
print(currDir)
## prepare simulation folder, if dir exits remove and create new one to be empty
Sim_Path = os.path.join(currDir, ProjectName)
if os.path.exists(Sim_Path):
	shutil.rmtree(Sim_Path)   # clear previous directory
	os.mkdir(Sim_Path)    # create empty simulation folder




mm = 0.001  # metres per mm unit

m = em.Simulation(ProjectName)
m.check_version("2.5.5")

# ── Materials ──────────────────────────────────────────────────────────────
diel_0 = em.Material(er=3.76, tand=0.009, color="#2ca02c", opacity=0.2)
diel_1 = em.Material(er=1.0, tand=0.0, color="#2ca02c", opacity=0.2)
diel_2 = em.Material(er=4.2, tand=0.02, color="#2ca02c", opacity=0.2)

# ── Geometry parameters ──────────────────────────────────────────────────
drill_r   = 0.125000 * mm  # via drill radius
pad_r     = 0.250000 * mm  # landing pad radius
antipad_r_default = 0.400000 * mm  # default clearance (antipad) radius
domain_hw = 2.7500 * mm  # domain half-width
signal_via_centers_mm = [(0.0, 0.0)]
plane_antipad_r_mm_by_layer = { 4: 0.400000 }

# ── Stackup layer volumes (Z=0 at top surface, going negative) ──────────
# Signal copper layer: L1 (Signal)  z=[-0.0350, 0.0000] mm
# (pads created and united with trace in the feed section below)

# Dielectric layer: Core  z=[-0.2350, -0.0350] mm
layer_1 = em.geo.Box(2*domain_hw, 2*domain_hw, 0.200000*mm,
    position=(-domain_hw, -domain_hw, -0.235000*mm),
    alignment=em.geo.Alignment.CORNER,
    name="layer_1")
layer_1.material = diel_0

# Dielectric layer: L2 (GND)  z=[-0.2700, -0.2350] mm
layer_2 = em.geo.Box(2*domain_hw, 2*domain_hw, 0.035000*mm,
    position=(-domain_hw, -domain_hw, -0.270000*mm),
    alignment=em.geo.Alignment.CORNER,
    name="layer_2")
layer_2.material = diel_1

# Dielectric layer: Prepreg  z=[-1.2700, -0.2700] mm
layer_3 = em.geo.Box(2*domain_hw, 2*domain_hw, 1.000000*mm,
    position=(-domain_hw, -domain_hw, -1.270000*mm),
    alignment=em.geo.Alignment.CORNER,
    name="layer_3")
layer_3.material = diel_2

# Reference copper plane: L3 (Power)  z=[-1.3050, -1.2700] mm
layer_4 = em.geo.Box(2*domain_hw, 2*domain_hw, 0.035000*mm,
    position=(-domain_hw, -domain_hw, -1.305000*mm),
    alignment=em.geo.Alignment.CORNER,
    name="layer_4")
layer_4.material = em.lib.PEC
_do_sig_clear = (0 < 4 < 6)
_do_stub_clear = (False and 6 < 4 <= -1)
if 4 in plane_antipad_r_mm_by_layer and (_do_sig_clear or _do_stub_clear):
    _ap_r = plane_antipad_r_mm_by_layer[4] * mm
    for _vi, (_vx, _vy) in enumerate(signal_via_centers_mm):
        _ap = em.geo.Cylinder(_ap_r, 0.035000*mm,
            cs=em.GCS.displace(_vx*mm, _vy*mm, -1.305000*mm),
            name=f"layer_4_antipad_{_vi}")
        layer_4 = em.geo.subtract(layer_4, _ap)

# Dielectric layer: Core  z=[-1.5050, -1.3050] mm
layer_5 = em.geo.Box(2*domain_hw, 2*domain_hw, 0.200000*mm,
    position=(-domain_hw, -domain_hw, -1.505000*mm),
    alignment=em.geo.Alignment.CORNER,
    name="layer_5")
layer_5.material = diel_0

# Signal copper layer: L4 (Signal)  z=[-1.5400, -1.5050] mm
# (pads created and united with trace in the feed section below)

# ── Signal via barrel ────────────────────────────────────────────────────
# From L1 (Signal) z_top=0.0000mm  to L4 (Signal) z_bot=-1.5400mm
via_barrel = em.geo.Cylinder(drill_r, 1.540000*mm,
    cs=em.GCS.displace(0, 0, -1.540000*mm),
    name="via_barrel")
via_barrel.material = em.lib.PEC

# ── Via holes used to clear intersected dielectric layers ───────────────
_diel_via_holes = []  # (x[m], y[m], r[m], z_bot[m], z_top[m])
for _vx, _vy in signal_via_centers_mm:
    _diel_via_holes.append((_vx*mm, _vy*mm, drill_r, -1.540000*mm, 0.000000*mm))

# ── Entry feed geometry ──────────────────────────────────────────────────
# Layer: L1 (Signal),  type=trace, angle=180.0°
trace_start = em.geo.Box(2.000000*mm, 0.250000*mm, 0.035000*mm,
    position=(0.214006*mm, -0.125000*mm, -0.035000*mm),
    alignment=em.geo.Alignment.CORNER,
    name="trace_start")
trace_start.material = em.lib.PEC
trace_start = em.geo.rotate(trace_start, c0=(0, 0, 0),
    ax=(0, 0, 1), angle=180.0000)
# Landing pads on entry signal layer — united with trace_start
for _vx, _vy in signal_via_centers_mm:
    _pad = em.geo.Cylinder(pad_r, 0.035000*mm,
        cs=em.GCS.displace(_vx*mm, _vy*mm, -0.035000*mm),
        name="entry_pad")
    _pad.material = em.lib.PEC
    trace_start = em.geo.add(trace_start, _pad)

# ── Exit feed geometry ───────────────────────────────────────────────────
# Layer: L4 (Signal),  type=trace, angle=0.0°
trace_end = em.geo.Box(2.000000*mm, 0.250000*mm, 0.035000*mm,
    position=(0.214006*mm, -0.125000*mm, -1.540000*mm),
    alignment=em.geo.Alignment.CORNER,
    name="trace_end")
trace_end.material = em.lib.PEC
# Landing pads on exit signal layer — united with trace_end
for _vx, _vy in signal_via_centers_mm:
    _pad = em.geo.Cylinder(pad_r, 0.035000*mm,
        cs=em.GCS.displace(_vx*mm, _vy*mm, -1.540000*mm),
        name="exit_pad")
    _pad.material = em.lib.PEC
    trace_end = em.geo.add(trace_end, _pad)

# ── Dielectric clearances for all crossing vias ─────────────────────────
# Dielectric via clearances on layer 1 (Core)
for _hi, (_hx, _hy, _hr, _hz_bot, _hz_top) in enumerate(_diel_via_holes):
    if not (_hz_top <= -0.235000*mm or _hz_bot >= -0.035000*mm):
        _dh = em.geo.Cylinder(_hr, 0.200000*mm,
            cs=em.GCS.displace(_hx, _hy, -0.235000*mm),
            name=f"layer_1_diel_clear_{_hi}")
        layer_1 = em.geo.subtract(layer_1, _dh)

# Dielectric via clearances on layer 2 (L2 (GND))
for _hi, (_hx, _hy, _hr, _hz_bot, _hz_top) in enumerate(_diel_via_holes):
    if not (_hz_top <= -0.270000*mm or _hz_bot >= -0.235000*mm):
        _dh = em.geo.Cylinder(_hr, 0.035000*mm,
            cs=em.GCS.displace(_hx, _hy, -0.270000*mm),
            name=f"layer_2_diel_clear_{_hi}")
        layer_2 = em.geo.subtract(layer_2, _dh)

# Dielectric via clearances on layer 3 (Prepreg)
for _hi, (_hx, _hy, _hr, _hz_bot, _hz_top) in enumerate(_diel_via_holes):
    if not (_hz_top <= -1.270000*mm or _hz_bot >= -0.270000*mm):
        _dh = em.geo.Cylinder(_hr, 1.000000*mm,
            cs=em.GCS.displace(_hx, _hy, -1.270000*mm),
            name=f"layer_3_diel_clear_{_hi}")
        layer_3 = em.geo.subtract(layer_3, _dh)

# Dielectric via clearances on layer 5 (Core)
for _hi, (_hx, _hy, _hr, _hz_bot, _hz_top) in enumerate(_diel_via_holes):
    if not (_hz_top <= -1.505000*mm or _hz_bot >= -1.305000*mm):
        _dh = em.geo.Cylinder(_hr, 0.200000*mm,
            cs=em.GCS.displace(_hx, _hy, -1.505000*mm),
            name=f"layer_5_diel_clear_{_hi}")
        layer_5 = em.geo.subtract(layer_5, _dh)

# ── Non-plane copper clearances for crossing vias ───────────────────────
# ── Lumped port sheets ───────────────────────────────────────────────────
# Port sheet = 2D Plate at the far end of each trace.
# Width = trace width, Height = distance to nearest reference plane.
# direction=(0,0,1) = E-field vertical (GND→signal).
# Port 1: far end of entry trace — height=1.2700mm
port1_sheet = em.geo.Plate(
    (-2.214006*mm, 0.125000*mm, -1.270000*mm),
    (-0.000000*mm, -0.250000*mm, 0),
    (0, 0, 1.270000*mm),
    name="port1_sheet")

# Port 2: far end of exit trace — height=0.2350mm
port2_sheet = em.geo.Plate(
    (2.214006*mm, -0.125000*mm, -1.540000*mm),
    (-0.000000*mm, 0.250000*mm, 0),
    (0, 0, 0.235000*mm),
    name="port2_sheet")


# ── Geometry finalisation ────────────────────────────────────────────────
m.commit_geometry()
m.view(labels=True)

# ── Simulation setup ─────────────────────────────────────────────────────
m.mw.set_frequency_range(0.0100e9, 10.0000e9, 11)

# ── Mesh ─────────────────────────────────────────────────────────────────
m.mw.set_resolution(0.250)  # fraction of max wavelength
m.settings.safe_mode = True



p1 = m.mw.bc.LumpedPort(port1_sheet, 1,
    width=0.250000*mm, height=1.270000*mm,
    direction=(0, 0, 1))

p2 = m.mw.bc.LumpedPort(port2_sheet, 2,
    width=0.250000*mm, height=0.235000*mm,
    direction=(0, 0, 1))

m.generate_mesh()
m.view(plot_mesh=True)


# ── Simulation ───────────────────────────────────────────────────────────
data = m.mw.run_sweep(False, n_workers=1)
m.save()

ResultTimeCode = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
data.scalar.grid.export_touchstone(f"{ProjectName}_{ResultTimeCode}.s2p", Z0ref=50, format="RI", custom_comments=[ProjectName,"SP Studio"], funit="HZ" )