from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Dict, List, Tuple

import numpy as np

from sparams_utility.models.circuit import CircuitDocument, CircuitPortRef
from sparams_utility.models.state import AppState


@dataclass(frozen=True)
class CircuitSolveResult:
    nports: int
    frequencies_hz: np.ndarray
    s_matrices: np.ndarray  # shape (nfreq, nports, nports)
    z0_ohm: np.ndarray  # shape (nports,)


def solve_circuit_network(document: CircuitDocument, state: AppState) -> CircuitSolveResult:
    frequencies = _build_frequency_grid(document)
    if frequencies.size == 0:
        raise ValueError("Sweep has no valid frequency points.")

    external_assignments = sorted(document.external_ports, key=lambda item: item.external_port_number)
    if not external_assignments:
        raise ValueError("At least one external port block is required.")

    uf = _UnionFind()
    for instance in document.instances:
        for port in range(1, instance.nports + 1):
            uf.add((instance.instance_id, port))

    for connection in document.connections:
        uf.union(connection.port_a.key(), connection.port_b.key())

    grounded_roots: set[Tuple[str, int]] = set()
    for instance in document.instances:
        if instance.block_kind != "gnd":
            continue
        root = uf.find((instance.instance_id, 1))
        grounded_roots.add(root)

    root_to_node: Dict[Tuple[str, int], int] = {}
    next_node = 0
    for instance in document.instances:
        for port in range(1, instance.nports + 1):
            root = uf.find((instance.instance_id, port))
            if root in grounded_roots:
                continue
            if root not in root_to_node:
                root_to_node[root] = next_node
                next_node += 1

    node_count = next_node
    if node_count == 0:
        raise ValueError("No active electrical nodes found in circuit.")

    external_nodes: List[int] = []
    z0_values: List[float] = []
    for assignment in external_assignments:
        key = assignment.port_ref.key()
        if key not in uf.parent:
            raise ValueError("An external port references a missing block port.")
        root = uf.find(key)
        if root in grounded_roots:
            raise ValueError("An external port cannot be tied directly to GND.")
        external_nodes.append(root_to_node[root])
        instance = document.get_instance(assignment.port_ref.instance_id)
        z0_values.append(float(instance.impedance_ohm) if instance is not None else 50.0)

    if len(set(external_nodes)) != len(external_nodes):
        raise ValueError("Two or more external ports are shorted together. Use distinct nodes for exported ports.")

    z0_array = np.array(z0_values, dtype=float)
    if np.any(z0_array <= 0.0):
        raise ValueError("External port impedance must be > 0.")

    touchstone_cache = _build_touchstone_cache(document, state)

    s_out = np.zeros((frequencies.size, len(external_nodes), len(external_nodes)), dtype=np.complex128)
    for idx, frequency in enumerate(frequencies):
        y_global = np.zeros((node_count, node_count), dtype=np.complex128)

        for instance in document.instances:
            if instance.block_kind in {"port_ground", "port_diff", "gnd"}:
                continue
            if instance.block_kind in {"lumped_r", "lumped_l", "lumped_c"}:
                _stamp_lumped(instance, frequency, uf, grounded_roots, root_to_node, y_global)
                continue
            if instance.block_kind == "touchstone":
                _stamp_touchstone(instance, frequency, uf, grounded_roots, root_to_node, y_global, touchstone_cache)

        y_ports = _reduce_to_external_ports(y_global, external_nodes)
        s_out[idx] = _y_to_s(y_ports, z0_array)

    return CircuitSolveResult(
        nports=len(external_nodes),
        frequencies_hz=frequencies,
        s_matrices=s_out,
        z0_ohm=z0_array,
    )


def to_touchstone_string(result: CircuitSolveResult) -> str:
    return to_touchstone_string_with_format(result, data_format="RI", frequency_unit="GHz")


def to_touchstone_string_with_format(
    result: CircuitSolveResult,
    *,
    data_format: str = "RI",
    frequency_unit: str = "GHz",
) -> str:
    fmt = data_format.upper()
    if fmt not in {"RI", "MA", "DB"}:
        raise ValueError(f"Unsupported Touchstone format '{data_format}'.")

    unit = frequency_unit.upper()
    scale = {
        "HZ": 1.0,
        "KHZ": 1e3,
        "MHZ": 1e6,
        "GHZ": 1e9,
    }.get(unit)
    if scale is None:
        raise ValueError(f"Unsupported frequency unit '{frequency_unit}'.")

    lines = [
        "! Generated by SPUtility circuit solver",
        f"# {unit} S {fmt} R 50",
    ]

    for f_idx, freq_hz in enumerate(result.frequencies_hz):
        freq_scaled = freq_hz / scale
        parts: List[str] = [f"{freq_scaled:.12g}"]
        for row in range(result.nports):
            for col in range(result.nports):
                value = result.s_matrices[f_idx, row, col]
                if fmt == "RI":
                    parts.append(f"{value.real:.12g}")
                    parts.append(f"{value.imag:.12g}")
                else:
                    magnitude = abs(value)
                    angle_deg = math.degrees(math.atan2(value.imag, value.real))
                    if fmt == "MA":
                        parts.append(f"{magnitude:.12g}")
                    else:
                        mag_db = -300.0 if magnitude <= 0.0 else 20.0 * math.log10(magnitude)
                        parts.append(f"{mag_db:.12g}")
                    parts.append(f"{angle_deg:.12g}")
        lines.append(" ".join(parts))

    return "\n".join(lines) + "\n"


def _build_frequency_grid(document: CircuitDocument) -> np.ndarray:
    fmin = float(document.sweep.fmin_hz)
    fmax = float(document.sweep.fmax_hz)
    fstep = float(document.sweep.fstep_hz)
    if fmin <= 0.0 or fmax < fmin or fstep <= 0.0:
        return np.array([], dtype=float)

    count = int(np.floor((fmax - fmin) / fstep)) + 1
    if count < 1:
        return np.array([], dtype=float)
    freqs = fmin + np.arange(count, dtype=float) * fstep
    if freqs[-1] < fmax:
        freqs = np.append(freqs, fmax)
    return freqs


def _build_touchstone_cache(document: CircuitDocument, state: AppState) -> Dict[str, Tuple[np.ndarray, np.ndarray, float]]:
    cache: Dict[str, Tuple[np.ndarray, np.ndarray, float]] = {}
    for instance in document.instances:
        if instance.block_kind != "touchstone":
            continue
        if instance.source_file_id in cache:
            continue
        loaded = state.get_file(instance.source_file_id)
        if loaded is None:
            raise ValueError(f"Missing Touchstone file for block '{instance.display_label}'.")

        points = loaded.data.points
        freqs = np.array([p.frequency_hz for p in points], dtype=float)
        s_cube = np.zeros((len(points), loaded.data.nports, loaded.data.nports), dtype=np.complex128)
        for f_idx, point in enumerate(points):
            for row in range(loaded.data.nports):
                for col in range(loaded.data.nports):
                    s_cube[f_idx, row, col] = point.s_matrix[row][col].complex_value
        cache[instance.source_file_id] = (
            freqs,
            s_cube,
            float(loaded.data.options.reference_resistance),
        )
    return cache


def _stamp_lumped(
    instance,
    frequency: float,
    uf: "_UnionFind",
    grounded_roots: set[Tuple[str, int]],
    root_to_node: Dict[Tuple[str, int], int],
    y_global: np.ndarray,
) -> None:
    port_a = (instance.instance_id, 1)
    port_b = (instance.instance_id, 2)
    root_a = uf.find(port_a)
    root_b = uf.find(port_b)

    if instance.block_kind == "lumped_r":
        impedance = complex(instance.impedance_ohm, 0.0)
    elif instance.block_kind == "lumped_l":
        impedance = complex(0.0, 2.0 * np.pi * frequency * instance.impedance_ohm)
    elif instance.block_kind == "lumped_c":
        if frequency <= 0.0:
            impedance = complex(1e18, 0.0)
        else:
            impedance = complex(0.0, -1.0 / (2.0 * np.pi * frequency * instance.impedance_ohm))
    else:
        return

    if abs(impedance) < 1e-18:
        admittance = complex(1e18, 0.0)
    else:
        admittance = 1.0 / impedance

    _stamp_admittance_between_nodes(root_a, root_b, admittance, grounded_roots, root_to_node, y_global)


def _stamp_touchstone(
    instance,
    frequency: float,
    uf: "_UnionFind",
    grounded_roots: set[Tuple[str, int]],
    root_to_node: Dict[Tuple[str, int], int],
    y_global: np.ndarray,
    cache: Dict[str, Tuple[np.ndarray, np.ndarray, float]],
) -> None:
    if instance.source_file_id not in cache:
        return
    freqs, s_cube, z0 = cache[instance.source_file_id]
    s_interp = _interpolate_s_matrix(freqs, s_cube, frequency)
    y_block = _s_to_y(s_interp, float(z0))

    roots = [uf.find((instance.instance_id, idx + 1)) for idx in range(instance.nports)]
    for i in range(instance.nports):
        for j in range(instance.nports):
            _stamp_general_admittance(
                roots[i],
                roots[j],
                y_block[i, j],
                grounded_roots,
                root_to_node,
                y_global,
            )


def _stamp_admittance_between_nodes(
    root_a: Tuple[str, int],
    root_b: Tuple[str, int],
    admittance: complex,
    grounded_roots: set[Tuple[str, int]],
    root_to_node: Dict[Tuple[str, int], int],
    y_global: np.ndarray,
) -> None:
    a_is_ground = root_a in grounded_roots
    b_is_ground = root_b in grounded_roots

    if not a_is_ground:
        ia = root_to_node[root_a]
        y_global[ia, ia] += admittance
    if not b_is_ground:
        ib = root_to_node[root_b]
        y_global[ib, ib] += admittance
    if not a_is_ground and not b_is_ground:
        ia = root_to_node[root_a]
        ib = root_to_node[root_b]
        y_global[ia, ib] -= admittance
        y_global[ib, ia] -= admittance


def _stamp_general_admittance(
    root_i: Tuple[str, int],
    root_j: Tuple[str, int],
    value: complex,
    grounded_roots: set[Tuple[str, int]],
    root_to_node: Dict[Tuple[str, int], int],
    y_global: np.ndarray,
) -> None:
    i_ground = root_i in grounded_roots
    j_ground = root_j in grounded_roots
    if i_ground:
        return
    ii = root_to_node[root_i]
    if j_ground:
        if root_i == root_j:
            y_global[ii, ii] += value
        return
    jj = root_to_node[root_j]
    y_global[ii, jj] += value


def _reduce_to_external_ports(y_global: np.ndarray, external_nodes: List[int]) -> np.ndarray:
    n_total = y_global.shape[0]
    ext = np.array(external_nodes, dtype=int)
    all_nodes = np.arange(n_total, dtype=int)
    int_nodes = np.array([n for n in all_nodes if n not in set(external_nodes)], dtype=int)

    y_ee = y_global[np.ix_(ext, ext)]
    if int_nodes.size == 0:
        return y_ee

    y_ei = y_global[np.ix_(ext, int_nodes)]
    y_ie = y_global[np.ix_(int_nodes, ext)]
    y_ii = y_global[np.ix_(int_nodes, int_nodes)]

    try:
        correction = y_ei @ np.linalg.solve(y_ii, y_ie)
    except np.linalg.LinAlgError:
        correction = y_ei @ (np.linalg.pinv(y_ii) @ y_ie)

    return y_ee - correction


def _s_to_y(s_matrix: np.ndarray, z0: float) -> np.ndarray:
    n = s_matrix.shape[0]
    ident = np.eye(n, dtype=np.complex128)
    a = ident + s_matrix
    b = ident - s_matrix
    try:
        inv_a = np.linalg.inv(a)
    except np.linalg.LinAlgError:
        inv_a = np.linalg.pinv(a)
    return (inv_a @ b) / z0


def _y_to_s(y_matrix: np.ndarray, z0_ports: np.ndarray) -> np.ndarray:
    n = y_matrix.shape[0]
    ident = np.eye(n, dtype=np.complex128)
    sqrt_z0 = np.diag(np.sqrt(z0_ports.astype(np.complex128)))
    a = sqrt_z0 @ y_matrix @ sqrt_z0
    left = ident - a
    right = ident + a
    try:
        inv_right = np.linalg.inv(right)
    except np.linalg.LinAlgError:
        inv_right = np.linalg.pinv(right)
    return left @ inv_right


def _interpolate_s_matrix(source_freqs: np.ndarray, s_cube: np.ndarray, target_freq: float) -> np.ndarray:
    if target_freq <= source_freqs[0]:
        return s_cube[0]
    if target_freq >= source_freqs[-1]:
        return s_cube[-1]

    idx = np.searchsorted(source_freqs, target_freq)
    f0 = source_freqs[idx - 1]
    f1 = source_freqs[idx]
    if f1 <= f0:
        return s_cube[idx]
    alpha = (target_freq - f0) / (f1 - f0)
    return (1.0 - alpha) * s_cube[idx - 1] + alpha * s_cube[idx]


class _UnionFind:
    def __init__(self) -> None:
        self.parent: Dict[Tuple[str, int], Tuple[str, int]] = {}

    def add(self, item: Tuple[str, int]) -> None:
        if item not in self.parent:
            self.parent[item] = item

    def find(self, item: Tuple[str, int]) -> Tuple[str, int]:
        parent = self.parent[item]
        if parent != item:
            self.parent[item] = self.find(parent)
        return self.parent[item]

    def union(self, a: Tuple[str, int], b: Tuple[str, int]) -> None:
        ra = self.find(a)
        rb = self.find(b)
        if ra != rb:
            self.parent[rb] = ra
